### PR TITLE
[AyusGup]: fixed Navbar icons not working issue

### LINKED ISSUE #28: [Bug]: The category options is not opening any items list
image

These icons are not working and do not open specified things

### PR DESCRIPTION
**Pull request by AyusGup**
1) Added @mui/styles to create custom styles
2) Added tags in product schema to provide items according to their category
**Final Document will look like**
Screenshot 2023-10-21 171838

**Changes Done**

https://github.com/adityaS011/ecommerce-clone/assets/127961367/a1ade93b-90eb-4cb7-a7f8-8f57acde70bf

Fixed #28

### CODE REVIEW

**Comment by AyusGup** [comment]
@adityaS011 all the checks are failing as schema is changed by me. please review the changes and merge it under hacktoberfest label

**Comment by adityaS011** [comment]
I can't merge it as it will result in deploy error

**Comment by adityaS011** [comment]
Great work Ayus but I think its not working after the merge

**Comment by AyusGup** [comment]
> Great work Ayus but I think its not working after the merge

can u exactly tell me where it is giving error so that i can fix it. As at my local host it's working properly but as there is a schema change in backend that's why i think netlify is unable to deploy it

**Pull request merged**
